# Generated by Django 4.0.3 on 2022-05-01 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_alter_women_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['id'], 'verbose_name': 'Известные мужчины', 'verbose_name_plural': 'Известные мужчины'},
        ),
    ]
