# Generated by Django 4.0.3 on 2022-05-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Men',
        ),
    ]
