# Generated by Django 4.0.3 on 2022-05-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_rename_men_women'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Women',
            new_name='Men',
        ),
    ]
