# Generated by Django 4.0.3 on 2022-05-01 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_rename_women_men'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Men',
            new_name='Women',
        ),
    ]
